#!/bin/sh

set -e

# Configure container

# The apk adds below can fail intermittently in colima with
# WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.18/main: No such file or directory
# if run immediately after a cache clear.

ln -fns /var/cache/apk /etc/apk/cache
apk add curl
apk add git
apk add jq
apk add ncurses
apk add ripgrep
apk add sqlite
apk add sudo
apk add uuidgen
apk add vim
apk add zsh

if [ -n "${HALFYAK_USERNAME}" ]
then
  # Create the user with no password and the shell zsh
  adduser -D -s /bin/zsh "${HALFYAK_USERNAME}"
  # Allow the user to sudo
  printf '%s ALL=(ALL) NOPASSWD: ALL\n' "${HALFYAK_USERNAME}" | EDITOR='tee -a' visudo -f /etc/sudoers.d/halfyak-etc
  # And switch to their home - note you can't (in POSIX) use ~"${HALFYAK_USERNAME}"
  cd "$(su -l "${HALFYAK_USERNAME}" -c pwd)"
else
  # Switch to root's home
  cd
fi

# Clone and setup as the user (default root), assumes HALFYAK_ETC_GIT set by dockerized-etc
# The safe.directory setting permits git to clone /mnt/etc.git despite the fact it is owned
# by another user. This is required since the user inside docker uid will typically not
# match the user on host uid.
su "${HALFYAK_USERNAME:-root}"<<END_SETUP
git config --global --add safe.directory /mnt/etc.git
git clone "${HALFYAK_ETC_GIT}"
~/etc/libexec/setup
END_SETUP

# Start a configured shell as the user (default root)
# Don't use `-l` because
# (a) Mostly i use non-login shells, so be like that
# (b) I want to keep the environment, notably TERM_PROGRAM
# (c) The shell is needed for root, since I don't want to chsh them
# (d) We wind SHLVL back to hide this script. The outer shell is gone according to ps
#     inside the container, and i want to be able to correctly flag perceived subshells in
#     my prompt. I considered resetting it, but reducing it by 1 seems more accurate. As i
#     read the code, zsh just sets it on start to 1 more than it found in the environment.
#     https://github.com/zsh-users/zsh/blob/5977d3cdd4b241ab7afff868ed58afc00b45c424/Src/params.c#L926
export SHLVL=$((SHLVL - 1))
exec su -s /bin/zsh "${HALFYAK_USERNAME:-root}"
