#!/bin/sh

set -e

# Configure container

# The apk adds below can fail intermittently in colima with
# WARNING: opening from cache https://dl-cdn.alpinelinux.org/alpine/v3.18/main: No such file or directory
# if run immediately after a cache clear.

ln -fns /var/cache/apk /etc/apk/cache
apk add git
apk add ncurses
apk add sqlite
apk add sudo
apk add uuidgen
apk add zsh

if [ -n "${HALFYAK_USERNAME}" ]
then
  # Create the user with no password and the shell zsh
  adduser -D -s /bin/zsh "${HALFYAK_USERNAME}"
  # Allow the user to sudo
  printf '%s ALL=(ALL) NOPASSWD: ALL\n' "${HALFYAK_USERNAME}" | EDITOR='tee -a' visudo -f /etc/sudoers.d/halfyak-etc
  # And switch to their home - note you can't (in POSIX) use ~"${HALFYAK_USERNAME}"
  cd "$(su -l "${HALFYAK_USERNAME}" -c pwd)"
else
  # Switch to root's home
  cd
fi

# Clone and setup as the user (default root), assumes HALFYAK_ETC_GIT set by dockerized-etc
su "${HALFYAK_USERNAME:-root}"<<END_SETUP
git clone "${HALFYAK_ETC_GIT}"
~/etc/libexec/setup
END_SETUP

# Start a configured shell as the user (default root)
# Don't use `-l` because
# (a) Mostly i use non-login shells, so be like that
# (b) I want to keep the environment, notably TERM_PROGRAM
# (c) The shell is needed for root, since I don't want to chsh them
exec su -s /bin/zsh "${HALFYAK_USERNAME:-root}"
