#!/bin/zsh

set -ex

HALFYAK_ETC_LIBEXEC="${$(print -P '%x'):A:h}"

printf '%s: Running daily tasks\n' "$(date)"

"${HALFYAK_ETC_LIBEXEC}"/daily-backup

printf '%s: Completed daily tasks\n' "$(date)"
