#!/bin/zsh -e

log() {
  local fmt="${1:?}"
  shift
  print -f "%s: ${fmt}\n" -- "$(date)" "$@"
}

fail() {
  log "$@"
  exit 1
}

BACKUP_ROOT=~/cloud/backup
if [[ ! -d "${BACKUP_ROOT}" ]]
then
  fail 'No backup root at %s, cannot backup' "${(q+)BACKUP_ROOT}"
else
  BACKUP_DIR="${BACKUP_ROOT}/$(date +'%Y-%m-%d')"
  log 'Backing up to %s' "${(q+)BACKUP_DIR}"

  mkdir "${BACKUP_DIR}" || fail 'Partial backup at %s, giving up' "${(q+)BACKUP_DIR}"

  sqlite3 "${HALFYAK_ETC_SQLITE_HISTORY_DB}" '.dump' \
    | bzip2 --stdout \
    > "${BACKUP_DIR}/HALFYAK_ETC_SQLITE_HISTORY_DB.dump.bz2"
  [[ 0 -eq "${#pipestatus:#0}" ]]

  cp "${HOME}/.docker/config.json" "${BACKUP_DIR}/docker-config.json"

  local size
  size="$(du -sh "${BACKUP_DIR}")"
  log 'Backup Size: %s' "${size}"
fi
