#!/bin/zsh -e

log() {
  local fmt="${1:?}"
  shift
  print -f "%s: ${fmt}\n" -- "$(date)" "$@"
}

fail() {
  log "$@"
  exit 1
}

BACKUP_ROOT=~/cloud/backup
if [[ ! -d "${BACKUP_ROOT}" ]]
then
  fail 'No backup root at %s, cannot snapshot' "${(q+)BACKUP_ROOT}"
else
  SNAPSHOT_DIR="${BACKUP_ROOT}/snapshot"
  log 'Snapshotting to %s' "${(q+)SNAPSHOT_DIR}"

  mkdir -p "${SNAPSHOT_DIR}" || fail 'Cannot create %s, giving up' "${(q+)SNAPSHOT_DIR}"

  for dir in ~/src/*(/)
  do
    local name="${dir##*/}"
    local snapshot="${SNAPSHOT_DIR}/src/${name}"
    mkdir -p "${snapshot}"
    git -C "${dir}" config get remote.origin.url > "${snapshot}/remote.origin.url"
  done

  asdf list > "${SNAPSHOT_DIR}/asdf"

  mkdir -p "${SNAPSHOT_DIR}/alfredapp"
  rsync --checksum --delete --links --recursive \
    ~/"Library/Application Support/Alfred/Alfred.alfredpreferences"/ \
    "${SNAPSHOT_DIR}/alfredapp/Alfred.alfredpreferences"/

  mkdir -p "${SNAPSHOT_DIR}/iterm"
  rsync --checksum --delete --links --recursive \
    ~/"Library/Preferences/com.googlecode.iterm2.plist" \
    "${SNAPSHOT_DIR}/iterm/com.googlecode.iterm2.plist"


  local size
  size="$(du -sh "${SNAPSHOT_DIR}")"
  log 'Snapshot Size: %s' "${size}"
fi
