#!/bin/zsh -f

# Start a new docker container with an alpine running my etc
# This is intended for lightweight basic testing

set -e

error() {
  printf '%s\n' "$@"
  exit 1
}

usage() {
  error "Usage: ${ZSH_ARGZERO} [ -c|--cwd ] [ -h|--help ] [ -k|--keep-going ] [ -u|--user USERNAME ] [ -- [ docker-run-option ... ] ]" \
    "  -c | --cwd: mount current working directory as /mnt/cwd" \
    "  -h | --help: show usage and exit" \
    "  -k | --keep-going: stay in docker even if setup fails (to permit in situ debugging)" \
    "  -u | --user USERNAME: create and run as given USERNAME" \
    "  docker-run-option: options passed through to docker run (before the image)"
}

while [ $# -ne 0 ]
do
  case "${1:?}" in
    -c|--cwd)
      HOST_CWD="${PWD}"
      DOCKER_CWD="/mnt/cwd"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -k|--keep-going)
      # Make this numeric - we might end up with levels of it ...
      HALFYAK_KEEPGOING=1
      shift
      ;;
    -u|--user)
      [ $# -ge 2 ] || error "Option $1 requires argument"
      HALFYAK_USERNAME="${2:?}"
      shift 2
      ;;
    --)
      shift
      break
      ;;
    -*)
      error "Unrecognized option: '${1}'"
      exit 1
      ;;
    *)
      break
      ;;
  esac
done

ETC_DIR="${$(print -P '%x'):A:h:h}"
HOST_ENTRYPOINT="${ETC_DIR}/libexec/docker/entrypoint"
HOST_GIT_REPO="${ETC_DIR}/.git"

CACHE_DIR="${XDG_CACHE_HOME:-${HOME}/.cache}/halfyak.org/etc"
HOST_APK_CACHE="${CACHE_DIR}/apk"

mkdir -p "${HOST_APK_CACHE}" "${HOST_ENTRYPOINT%/*}"

DOCKER_ENTRYPOINT="/mnt/entrypoint"
DOCKER_GIT_REPO="/mnt/etc.git"

DOCKER_APK_CACHE="/var/cache/apk"

docker run --rm --interactive --tty \
  --entrypoint "${DOCKER_ENTRYPOINT}" \
  --env HALFYAK_ETC_GIT="${DOCKER_GIT_REPO}" \
  ${TERM_PROGRAM+--env} ${TERM_PROGRAM+"TERM_PROGRAM=${TERM_PROGRAM}"} \
  ${HALFYAK_KEEPGOING+--env} ${HALFYAK_KEEPGOING+"HALFYAK_KEEPGOING=${HALFYAK_KEEPGOING}"} \
  ${HALFYAK_USERNAME+--env} ${HALFYAK_USERNAME+"HALFYAK_USERNAME=${HALFYAK_USERNAME}"} \
  --hostname "dockerized-etc" \
  --volume "${HOST_APK_CACHE}:${DOCKER_APK_CACHE}" \
  --volume "${HOST_ENTRYPOINT}:${DOCKER_ENTRYPOINT}" \
  --volume "${HOST_GIT_REPO}:${DOCKER_GIT_REPO}" \
  ${HOST_CWD+--volume} ${HOST_CWD+"${HOST_CWD}:${DOCKER_CWD}"} \
  "$@" \
  alpine:latest
