#!/bin/zsh

set -ex

HALFYAK_ETC_LIBEXEC="${$(print -P '%x'):A:h}"

printf '%s: Running weekly tasks\n' "$(date)"

# Check for warehoused change
"${HALFYAK_ETC_LIBEXEC}/git-hygiene" ~/etc

# Brew maintenance
"${HALFYAK_ETC_LIBEXEC}/brew-backup-update-upgrade"

# Validate mailto: handler set correctly
"${HALFYAK_ETC_LIBEXEC}/mailto-handler-check"

printf '%s: Completed weekly tasks\n' "$(date)"
