## Establish file system context
# These intentionally are not exported - they're just for this script to find things
# Prompt expand %x to get current file, absolutize
ZSHENV="${$(print -P '%x'):A}"
# We want the directory often enough also
ETC_ZSH_DIR="${ZSHENV:h}"

## Shell history in a sqlite database
# This must be set up in zshenv - although most usage is interactive, the etc/libexec/setup.zsh
# script is run non-interactively when doing exploratory testing via etc/libexec/dockerized-etc.zsh
# Location of db
export HALFYAK_ETC_SQLITE_HISTORY_DB="${HOME}/.local/share/halfyak/etc/zsh/history.sqlite3"
# Main driver script
export HALFYAK_ETC_SQLITE_HISTORY="${ETC_ZSH_DIR}/libexec/sqlite-history.zsh"
