# vi mode
bindkey -v
# bindings for insert mode
bindkey "^J" history-beginning-search-forward
bindkey "^K" history-beginning-search-backward
bindkey "^X" vi-cmd-mode
# According to my reading of https://en.wikipedia.org/wiki/ANSI_escape_code (under `Terminal input sequences`),
# these are the vt keycodes. I've set the corresponding keystroke directly in the iTerm config to ensure that
# they're right locally
bindkey "\e[3;3~" backward-delete-word # Alt-Delete
bindkey "\e[3;9~" backward-kill-line   # Cmd-Delete
# bindings for command mode
# bindkey -a ...

# Prompt expand %x to get current file, absolutize, head (i.e. dirname)
ZSHRC_DIR="${$(print -P '%x'):A:h}"

# Sundry zsh options
setopt AUTO_PUSHD
setopt GLOB_DOTS
setopt EXTENDED_GLOB
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
setopt INC_APPEND_HISTORY
setopt NO_AUTO_MENU
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_MINUS
setopt RC_QUOTES

# Sundry zsh parameters
DIRSTACKSIZE=48
HISTFILE="${ZSHRC_DIR}"/history
HISTSIZE=1000
SAVEHIST=1000

# Don't export PS variables, because other shells don't understand the zsh escapes
# Don't forget to
#   setopt PROMPT_SUBST
# if you once again set variables in precmd that are used in the prompt
() {
  # Include a note if running dockerized.
  # Probably would be good to extend this to "ssh'd in", etc.
  [[ -e /.dockerenv ]] && local notify_docker=" docker"
  PS1="%F{red}%B:${notify_docker-};%b%f "
  PS2=':%_; '
}

# Autocompletion configuration
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*:*:*:*:messages' format "%d"

autoload -U +X compinit && compinit
# I've experimented with
#   setopt automenu
#   zstyle ':completion:*' menu select
# to get arrow selected completion, but i need to tune/train more to like it
